server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


rsa:
  key:
    pubKeyFile: "G:\\resources\\springboot_demo\\spring_security\\springboot_security_parent\\raptor_common\\id_key_rsa.pub"
    priKeyFile: "G:\\resources\\springboot_demo\\spring_security\\springboot_security_parent\\raptor_common\\id_key_rsa"