spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

logging:
  level:
    com.raptor.springboot_security_jsp: debug

mybatis:
  type-aliases-package: com.raptor.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
